controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

oauth_check:
    path: /oauth/check
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
